name: Python CI

on:
  push:
    branches:
        - main
  pull_request:
    branches: 
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        #Step 1 : Checkout the code from the repository
        - name: Checkout code
          uses: actions/checkout@v2

        #Step 2 : Setup the python environment
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'

        #Step 3 : Install the dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        #Step4 4 : Run tests
        - name: Run tests
          run : pytest